### PR TITLE
Feature: Process Twilio Programmable Messaging webhooks

### PR DESCRIPTION
**Pull request by adamsrog**
Hello,

I've updated this package so it now functions with Twilio's Programmable Messaging webhooks. Fairly simple fix, just needed to make a small change in `src/ProcessTwilioWebhookJob.php` so it checked for `SmsStatus`, not just `CallStatus`. If there are more Twilio services, these could be added to the array of keys to check for. I've only used Programmable Voice and Messaging though.

Additionally, I had to adjust `src/WebhookSignature.php` so it could function properly with `statusCallback` URLs that contain URL parameters. For example, if you need to pass some information to be included when processing the webhook, (i.e. https://yoursite.com/webhooks/twilio.com?log_id=22&user_id=15), it was failing the verification check. The solution I used was to grab the URL parameters from the request URL, and then remove that data from the request. When this is done, the verification checks once again work properly.

For example, when processing a webhook using that URL, this is what `$request->all()` would look like:
```
$request->all(): Array
(
    [MessagingServiceSid] => MGxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    [ApiVersion] => 2010-04-01
    [MessageStatus] => delivered
    [RawDlrDoneDate] => 2409152252
    [SmsSid] => SMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    [SmsStatus] => delivered
    [To] => +13217654321
    [From] => +13211234567
    [MessageSid] => SMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    [AccountSid] => ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    [log_id] => 22
    [user_id] => 15
)
```
Because of those two additional parameters at the end (`log_id` and `user_id`), the verification would fail. Twilio does not take those into account when generating the signature it checks against. However, if removed, verification will be successful.

I've updated the readme to fix a few mentions of Mailgun (instead of Twilio) and also added some event types used in Programmable Messaging with some links to documentation. Finally, I added some information on using URL parameters in the callback URLs. 

Roger

## Summary by CodeRabbit

- **New Features**
	- Enhanced documentation for Twilio webhook handling, including detailed event types and logging information.
	- Introduced the ability to add metadata to webhook calls via URL parameters.

- **Bug Fixes**
	- Improved signature verification process for webhook requests, increasing accuracy.

- **Documentation**
	- Updated references from Mailgun to Twilio for consistency.
	- Added sections to clarify event types and logging scope for developers.

### CODE REVIEW

**Comment by nickfls** [comment]
@adamsrog would you consider adjusting the tests?

**Comment by adamsrog** [comment]
@nickfls yup, I've updated it now to fix the existing tests, as well as added two more tests. They're passing now.

**Comment by adamsrog** [comment]
@nickfls Is that sufficient or is there other tests you'd like me to write?

**Comment by cyrillkalita** [comment]
Let me get to the computer and I'll merge it right away

**Review by cyrillkalita — APPROVED** [review]

**Pull request merged**
